export const todasLasCuentas = [
    'MERCADERÍAS','PAPELERÍA Y ÚTILES DE ESCRITORIO','CAJA', 'ARTÍCULOS DE COMPUTACIÓN','DEUDORES VARIOS','INMUEBLES','DOCUMENTOS A COBRAR','BANCO','RODADOS','DEUDORES POR VENTAS','MUEBLES Y ÚTILES','INSTALACIONES','CHEQUE DIFERIDO',
    'PROVEEDORES','ACREEDORES VARIOS','FALTANTE DE CAJA','ALQUILERES PERDIDOS','INTERESES PERDIDOS','COSTO VENTA DE MERCADERÍAS','FLETES','LUZ Y TELÉFONO','SEGUROS','PAPELERÍA Y ÚTILES CONSUMIDOS','FALTANTE DE MERCADERÍA'
    ,'SOBRANTES DE CAJA','VENTAS','INTERESES GANADOS','ALQUILERES GANADOS','CAPITAL'
]
